# Generated by Django 3.2.9 on 2021-11-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Bus_list',
        ),
    ]
