# Generated by Django 3.2.9 on 2021-11-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_bus_bus_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus_list',
            old_name='Date',
            new_name='DATE',
        ),
        migrations.RenameField(
            model_name='bus_list',
            old_name='From',
            new_name='FROM',
        ),
        migrations.RenameField(
            model_name='bus_list',
            old_name='Price',
            new_name='PRICE',
        ),
        migrations.RenameField(
            model_name='bus_list',
            old_name='To',
            new_name='TO',
        ),
    ]
