# Generated by Django 3.2.9 on 2021-11-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20211124_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='')),
                ('package', models.IntegerField()),
                ('desc', models.TextField()),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.bus_list')),
            ],
        ),
    ]
