# Generated by Django 3.2.9 on 2021-11-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_list',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
