# Generated by Django 3.2.9 on 2021-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20211125_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='food',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='local',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='no_peaple',
            field=models.IntegerField(null=True),
        ),
    ]
